Update requirements.txt to work with pipenv (#490)
Before this commit: 
pipenv install -r requirements/requirements.txt
...
ValueError: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+https://github.com/EleutherAI/lm-evaluation-harness.git#egg=<package-name>.

After: <success>